/* eslint-disable import/order */
/* eslint-disable import/extensions */
/* eslint-disable import/no-unresolved */
import { AuthContext } from '@/providers/authProvider';
import Router from 'next/router';
import Head from 'next/head';
import { useContext, useEffect } from 'react';

export default function Home() {
  const { loading, isLogin } = useContext(AuthContext);

  useEffect(() => {
    if (!loading && !isLogin) {
      Router.push('/login');
    }
  }, [loading]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="w-full h-screen grid items-center justify-center">{loading ? <p className="font-bold text-2xl">Loading....</p> : <p className="font-bold text-2xl">Welcome</p>}</div>
      </main>
    </>
  );
}
